version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evol-app
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=development
    depends_on:
      - db
  db:
    image: postgres
    container_name: evol-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=evol
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: evol-pgadmin
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@evol.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db

volumes:
  postgres-data: